name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 1 * * *'
env:
  CXX: "g++-4.8"
jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: olafurpg/setup-scala@v13
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v6
    - run: sudo apt-get update
    - run: sudo apt-get install -y build-essential
    - run: sudo apt-get install gcc-4.8
    - run: sudo apt-get install g++-4.8
    - run: sudo apt-get install graphviz
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: '14.15.1'
    - run: npm install
    - run: npm ci
    - run: npm install svgexport -g
    - run: |
        wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/614d94496efdcf960871429e1c090c56d2018f68/setup/linux-installer.py |
        python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)" >/dev/null
    - run: |
        export PATH="~/calibre-bin/calibre/:$HOME/calibre-bin/calibre/:$PATH"
        sbt -v scalazDiagram build epub
    - run: mv book.epub honkit/_book/scalaz-docs.epub
    - run: find . -name "*.class" | xargs rm -rf
    - run: find . -name target | xargs rm -rf
    - name: push to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.2.0
      if: ${{ !github.event.repository.fork && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: honkit/_book/
        CLEAN: true
