name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 1 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: adopt
    - run: sudo apt-get update
    - run: sudo apt-get install graphviz libegl1 libopengl0
    - uses: actions/setup-node@v3.8.0
      with:
        node-version: '14.15.1'
    - run: npm install
    - run: npm ci
    - run: npm install svgexport -g
    - run: |
        wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/28c3422398e47e802b43dc026c27189ec9ef5050/setup/linux-installer.py |
        python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)" >/dev/null
    - run: |
        export PATH="~/calibre-bin/calibre/:$HOME/calibre-bin/calibre/:$PATH"
        sbt -v scalazDiagram build
    - run: find . -name "*.class" | xargs rm -rf
    - run: find . -name target | xargs rm -rf
    - name: push to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      if: ${{ github.repository_owner == 'xuwei-k' && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: honkit/_book/
        CLEAN: true
