name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 1 * * *'
env:
  CXX: "g++-4.8"
jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v5
    - run: sudo apt-get update
    - run: sudo apt-get install -y build-essential
    - run: sudo apt-get install gcc-4.8
    - run: sudo apt-get install g++-4.8
    - run: sudo apt-get install graphviz
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: '12.18.2' # https://github.com/nodejs/node/issues/34529
    - run: npm install -g npm
    - run: npm ci
    - run: npm install svgexport -g
    - run: sbt -v scalazDiagram build
    - run: find . -name "*.class" | xargs rm -rf
    - run: find . -name target | xargs rm -rf
    - name: push to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      if: ${{ !github.event.repository.fork && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: gitbook/_book/
        CLEAN: true
